# Credict Card Fruad Detection

## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
#loading the dataset
df = pd.read_csv('creditcard_2023.csv')

In [3]:
df.head()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-0.260648,-0.469648,2.496266,-0.083724,0.129681,0.732898,0.519014,-0.130006,0.727159,...,-0.110552,0.217606,-0.134794,0.165959,0.126280,-0.434824,-0.081230,-0.151045,17982.10,0
1,1,0.985100,-0.356045,0.558056,-0.429654,0.277140,0.428605,0.406466,-0.133118,0.347452,...,-0.194936,-0.605761,0.079469,-0.577395,0.190090,0.296503,-0.248052,-0.064512,6531.37,0
2,2,-0.260272,-0.949385,1.728538,-0.457986,0.074062,1.419481,0.743511,-0.095576,-0.261297,...,-0.005020,0.702906,0.945045,-1.154666,-0.605564,-0.312895,-0.300258,-0.244718,2513.54,0
3,3,-0.152152,-0.508959,1.746840,-1.090178,0.249486,1.143312,0.518269,-0.065130,-0.205698,...,-0.146927,-0.038212,-0.214048,-1.893131,1.003963,-0.515950,-0.165316,0.048424,5384.44,0
4,4,-0.206820,-0.165280,1.527053,-0.448293,0.106125,0.530549,0.658849,-0.212660,1.049921,...,-0.106984,0.729727,-0.161666,0.312561,-0.414116,1.071126,0.023712,0.419117,14278.97,0

In [4]:
df.tail()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
568625,568625,-0.833437,0.061886,-0.899794,0.904227,-1.002401,0.481454,-0.370393,0.189694,-0.938153,...,0.167503,0.419731,1.288249,-0.900861,0.560661,-0.006018,3.308968,0.081564,4394.16,1
568626,568626,-0.670459,-0.202896,-0.068129,-0.267328,-0.133660,0.237148,-0.016935,-0.147733,0.483894,...,0.031874,0.388161,-0.154257,-0.846452,-0.153443,1.961398,-1.528642,1.704306,4653.40,1
568627,568627,-0.311997,-0.004095,0.137526,-0.035893,-0.042291,0.121098,-0.070958,-0.019997,-0.122048,...,0.140788,0.536523,-0.211100,-0.448909,0.540073,-0.755836,-0.487540,-0.268741,23572.85,1
568628,568628,0.636871,-0.516970,-0.300889,-0.144480,0.131042,-0.294148,0.580568,-0.207723,0.893527,...,-0.060381,-0.195609,-0.175488,-0.554643,-0.099669,-1.434931,-0.159269,-0.076251,10160.83,1
568629,568629,-0.795144,0.433236,-0.649140,0.374732,-0.244976,-0.603493,-0.347613,-0.340814,0.253971,...,0.534853,-0.291514,0.157303,0.931030,-0.349423,-1.090974,-1.575113,0.722936,21493.92,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568630 entries, 0 to 568629
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      568630 non-null  int64
 1   V1      568630 non-null  float64
 2   V2      568630 non-null  float64
 3   V3      568630 non-null  float64
 4   V4      568630 non-null  float64
 5   V5      568630 non-null  float64
 6   V6      568630 non-null  float64
 7   V7      568630 non-null  float64
 8   V8      568630 non-null  float64
 9   V9      568630 non-null  float64
 10  V10     568630 non-null  float64
 11  V11     568630 non-null  float64
 12  V12     568630 non-null  float64
 13  V13     568630 non-null  float64
 14  V14     568630 non-null  float64
 15  V15     568630 non-null  float64
 16  V16     568630 non-null  float64
 17  V17     568630 non-null  float64
 18  V18     568630 non-null  float64
 19  V19     568630 non-null  float64
 20  V20     568630 non-null  float64
 21  V21     568630 non-null  float64
 22  V22     568630 non-null  float64
 23  V23     568630 non-null  float64
 24  V24     568630 non-null  float64
 25  V25     568630 non-null  float64
 26  V26     568630 non-null  float64
 27  V27     568630 non-null  float64
 28  V28     568630 non-null  float64
 29  Amount  568630 non-null  float64
 30  Class   568630 non-null  int64
dtypes: float64(29), int64(2)
memory usage: 134.5 MB

In [6]:
#distribution of legit traansction and fruad transcation
df['Class'].value_counts()

0    284315
1    284315
Name: Class, dtype: int64

# In this dataset

### Class = 0 --> Legit Transaction

### Class = 1 --> Fraud Transaction

In [7]:
#Separate Data for Analysis
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [8]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(284315, 31)

In [9]:
#Statistical measures of data
legit.Amount.describe()

count    284315.000000
mean      12026.313506
std        6929.500715
min          50.120000
25%        6034.540000
50%       11996.900000
75%       18040.265000
max       24039.930000
Name: Amount, dtype: float64

In [10]:
fraud.Amount.describe()

count    284315.000000
mean      12057.601763
std        6909.750891
min          50.010000
25%        6074.640000
50%       12062.450000
75%       18033.780000
max       24039.930000
Name: Amount, dtype: float64

In [11]:
#compare the value of both class
df.groupby('Class').mean()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,142442.987714,0.505761,-0.491878,0.682095,-0.735981,0.338639,0.435088,0.491234,-0.144294,0.585522,...,-0.179851,-0.10964,-0.014098,-0.010255,0.130107,-0.061847,-0.071052,-0.214002,-0.102024,12026.313506
1,426186.012286,-0.505761,0.491878,-0.682095,0.735981,-0.338639,-0.435088,-0.491234,0.144294,-0.585522,...,0.179851,0.10964,0.014098,0.010255,-0.130107,0.061847,0.071052,0.214002,0.102024,12057.601763

# UnderSampling

### Build a sample dataset for simliar distribution of Legit & Fraud Transaction.

### Number of Fraud Transaction --> 492

In [12]:
##legit_sample = legit.sample(n=492)

### Concating two dataframes

In [13]:
##new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [14]:
##new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
216050,140329.0,-0.810941,-4.858027,-1.864581,2.574220,-2.088573,0.133007,1.304571,-0.331732,1.111510,...,1.080891,0.046391,-1.181621,-0.067574,-0.533356,-0.627234,-0.217621,0.213063,1440.00,0
82031,59209.0,-0.946024,0.754324,1.727620,0.693752,0.306980,-0.509008,0.805728,-0.076353,-0.701190,...,0.103467,0.334860,0.095383,0.392633,-0.047518,-0.467755,0.030666,0.128033,41.70,0
204762,135437.0,-1.412455,2.284040,-1.577869,-1.646252,1.322297,-1.330159,1.860116,-0.600979,1.058498,...,-0.047403,0.718469,-0.298352,-0.738753,0.124452,0.139758,0.967597,0.463393,0.77,0
50487,44512.0,-1.298894,1.225182,1.114799,-0.213046,1.289151,-1.264462,0.430055,-0.924419,-0.856060,...,0.718587,-0.395691,-0.729595,0.348274,0.406290,0.287359,0.111050,0.083050,0.76,0
232969,147390.0,0.521433,-2.841418,-1.742302,0.453598,-0.140805,2.049435,0.168956,0.427573,0.847506,...,0.074907,-1.215081,-0.115812,-0.941383,-1.037812,0.152209,-0.139669,0.055100,716.91,0

In [15]:
##new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [16]:
##new_dataset['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [25]:
##new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,93306.878049,0.166897,0.034659,-0.007674,0.008820,-0.104120,0.033431,0.017882,0.017183,0.086949,...,-0.007983,-0.028126,0.024140,-0.022182,0.004287,0.011673,0.024372,0.005863,-0.010534,89.127459
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

### Spiliting data into Features & Targets

In [12]:
X = df.drop(columns='Class', axis=1)
Y = df['Class']

In [13]:
print(X)

            id        V1        V2        V3        V4        V5        V6  \
0            0 -0.260648 -0.469648  2.496266 -0.083724  0.129681  0.732898
1            1  0.985100 -0.356045  0.558056 -0.429654  0.277140  0.428605
2            2 -0.260272 -0.949385  1.728538 -0.457986  0.074062  1.419481
3            3 -0.152152 -0.508959  1.746840 -1.090178  0.249486  1.143312
4            4 -0.206820 -0.165280  1.527053 -0.448293  0.106125  0.530549
...        ...       ...       ...       ...       ...       ...       ...
568625  568625 -0.833437  0.061886 -0.899794  0.904227 -1.002401  0.481454
568626  568626 -0.670459 -0.202896 -0.068129 -0.267328 -0.133660  0.237148
568627  568627 -0.311997 -0.004095  0.137526 -0.035893 -0.042291  0.121098
568628  568628  0.636871 -0.516970 -0.300889 -0.144480  0.131042 -0.294148
568629  568629 -0.795144  0.433236 -0.649140  0.374732 -0.244976 -0.603493

              V7        V8        V9  ...       V20       V21       V22  \
0       0.519014 -0.130006  0.727159  ...  0.091202 -0.110552  0.217606
1       0.406466 -0.133118  0.347452  ... -0.233984 -0.194936 -0.605761
2       0.743511 -0.095576 -0.261297  ...  0.361652 -0.005020  0.702906
3       0.518269 -0.065130 -0.205698  ... -0.378223 -0.146927 -0.038212
4       0.658849 -0.212660  1.049921  ...  0.247237 -0.106984  0.729727
...          ...       ...       ...  ...       ...       ...       ...
568625 -0.370393  0.189694 -0.938153  ... -0.751011  0.167503  0.419731
568626 -0.016935 -0.147733  0.483894  ... -0.550260  0.031874  0.388161
568627 -0.070958 -0.019997 -0.122048  ... -0.076417  0.140788  0.536523
568628  0.580568 -0.207723  0.893527  ...  0.288186 -0.060381 -0.195609
568629 -0.347613 -0.340814  0.253971  ... -0.621378  0.534853 -0.291514

             V23       V24       V25       V26       V27       V28    Amount
0      -0.134794  0.165959  0.126280 -0.434824 -0.081230 -0.151045  17982.10
1       0.079469 -0.577395  0.190090  0.296503 -0.248052 -0.064512   6531.37
2       0.945045 -1.154666 -0.605564 -0.312895 -0.300258 -0.244718   2513.54
3      -0.214048 -1.893131  1.003963 -0.515950 -0.165316  0.048424   5384.44
4      -0.161666  0.312561 -0.414116  1.071126  0.023712  0.419117  14278.97
...          ...       ...       ...       ...       ...       ...       ...
568625  1.288249 -0.900861  0.560661 -0.006018  3.308968  0.081564   4394.16
568626 -0.154257 -0.846452 -0.153443  1.961398 -1.528642  1.704306   4653.40
568627 -0.211100 -0.448909  0.540073 -0.755836 -0.487540 -0.268741  23572.85
568628 -0.175488 -0.554643 -0.099669 -1.434931 -0.159269 -0.076251  10160.83
568629  0.157303  0.931030 -0.349423 -1.090974 -1.575113  0.722936  21493.92

[568630 rows x 30 columns]

In [14]:
print(Y)

0         0
1         0
2         0
3         0
4         0
         ..
568625    1
568626    1
568627    1
568628    1
568629    1
Name: Class, Length: 568630, dtype: int64

## Split the data into Training data & Testing data

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [16]:
print(X.shape, X_train.shape, X_test.shape)

(568630, 30) (454904, 30) (113726, 30)

In [18]:
print(Y.shape, Y_train.shape, Y_test.shape)

(568630,) (454904,) (113726,)

# Model Training

## Logistics Regression

In [19]:
model = LogisticRegression()

In [20]:
model.fit(X_train, Y_train)

C:\Users\manth\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

## Model Evaluation

### Accuracy Score

In [21]:
# accuracy on traiining data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [22]:
print("Accuracy on Training data :" ,training_data_accuracy )

Accuracy on Training data : 0.9952099783690624

In [23]:
#accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [24]:
print('Accuracy score on Test data : ', test_data_accuracy)

Accuracy score on Test data :  0.9955067442801119